### ISSUE TITLE
When code is coming?

### ISSUE THREAD

**Issue by xiaofeifei-1** [KubeEdge4Robotics/ScaleNav#2]

**Comment by CameronChen07** [comment]
Thanks for your waiting, recently I am busy in doing a new project. And releasing the code requires an official review of the company where I did my intern, which takes time to prepare. Now I have finished my new project and will start to prepare for the official code release procedure. Thanks for your attention.

**Comment by CameronChen07** [comment]
If you need the code in urgency, you can contact me via my email.
